controller:
  service:
    type: LoadBalancer
    annotations:
      load-balancer.hetzner.cloud/name: nginx-ingress
      load-balancer.hetzner.cloud/use-private-ip: true
      load-balancer.hetzner.cloud/location: fsn1
      load-balancer.hetzner.cloud/type: lb11
